### ISSUE TITLE
p2pcam does not have a version key in the manifest file

### ISSUE THREAD

**Issue by smithbill17** [indykoning/home-assistant-p2pcam#2]
Custom integration will not load. Log file states:

`2022-02-01 14:20:19 ERROR (SyncWorker_1) [homeassistant.loader] The custom integration 'p2pcam' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`

Home Assistant: 2021.12.10

**Comment by smithbill17** [comment]
I tried adding a version to the manifest.json file which allowed the integration to load, but Home Assistant just generates errors & the entity/card just doesn't work.

**Comment by indykoning** [comment]
What errors does it generate?
Sadly i no longer have the camera i used to test, so i can no longer reproduce the errors myself

**Comment by smithbill17** [comment]
Well, that is a little difficult to figure out, but pasted below is some of the stuff appearing in my Home Assistant log:

```
2022-02-01 15:23:04 WARNING (MainThread) [homeassistant.components.camera] The camera entity camera.cam_button does not support requesting width and height, please open an issue with the integration author

2022-02-01 15:23:18 ERROR (MainThread) [aiohttp.server] Error handling request

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 106, in receiveControlPacket

nbbytes, addr = self.sock.recvfrom_into(output, 1024)

socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 190, in initialize

nbReceived = self.receiveControlPacket(self.buffer)

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 112, in receiveControlPacket

raise socket.timeout

socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 208, in initialize

raise RestartException("Socket timeout 1", 1)

p2pcam.RestartException: 'Socket timeout 1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 106, in receiveControlPacket

nbbytes, addr = self.sock.recvfrom_into(output, 1024)

socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 190, in initialize

nbReceived = self.receiveControlPacket(self.buffer)

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 112, in receiveControlPacket

raise socket.timeout

socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 208, in initialize

raise RestartException("Socket timeout 1", 1)

p2pcam.RestartException: 'Socket timeout 1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 106, in receiveControlPacket

nbbytes, addr = self.sock.recvfrom_into(output, 1024)

socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 190, in initialize

nbReceived = self.receiveControlPacket(self.buffer)

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 112, in receiveControlPacket

raise socket.timeout

socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 208, in initialize

raise RestartException("Socket timeout 1", 1)

p2pcam.RestartException: 'Socket timeout 1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 106, in receiveControlPacket

nbbytes, addr = self.sock.recvfrom_into(output, 1024)

socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 190, in initialize

nbReceived = self.receiveControlPacket(self.buffer)

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 112, in receiveControlPacket

raise socket.timeout

socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 208, in initialize

raise RestartException("Socket timeout 1", 1)

p2pcam.RestartException: 'Socket timeout 1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 106, in receiveControlPacket

nbbytes, addr = self.sock.recvfrom_into(output, 1024)

socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 190, in initialize

nbReceived = self.receiveControlPacket(self.buffer)

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 112, in receiveControlPacket

raise socket.timeout

socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request

resp = await request_handler(request)

File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle

resp = await handler(request)

File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle

result = await result

File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 629, in get

return await self.handle(request, camera)

File

"/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 647, in handle

image = await _async_get_image(

File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 171, in _async_get_image

image_bytes = await camera.async_camera_image()

File "/config/custom_components/p2pcam/camera.py", line 56, in async_camera_image

return self.camera.retrieveImage()

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 270, in retrieveImage

self.initialize()

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 262, in initialize

self.initialize()

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 262, in initialize

self.initialize()

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 262, in initialize

self.initialize()

[Previous line repeated 1 more time]

File "/usr/local/lib/python3.9/site-packages/p2pcam/__init__.py", line 206, in initialize

raise Exception('Not responding')

Exception: Not responding
```

**Comment by smithbill17** [comment]
No update on resolving this issue?

**Comment by smithbill17** [comment]
I guess this component is no longer maintained?
